### ISSUE TITLE
Charge Time Value in Enemy Class

### ISSUE THREAD

**Issue by ProgrammingIncluded** [SuperKaitoKid/MGA#1]
Enemy class for charge times should have time instrumentation. What exactly is the time, milliseconds, seconds, etc...

**Comment by Merrycatch22** [comment]
I'm not sure what's wrong, as chargePeriod is based off of dTime in tick anyhow, so chargePeriod is exactly chargeTime seconds. Or maybe I'm not understanding what time instrumentation means.

**Comment by ProgrammingIncluded** [comment]
Sorry, what I am trying to say is to make sure to define what units you are basing charge period off of. I am not sure whether chargePeriod is in seconds or another unit of measurement. How would one be able to intuitively tell what value they should set chargePeriod to have a desired charge time? 

Do you mean that chargePeriod is based off of seconds?

**Comment by ProgrammingIncluded** [comment]
Issue has been discussed fully in person and has been fixed.
